# Generated by Django 4.1.9 on 2023-10-20 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_logo', models.ImageField(blank=True, null=True, upload_to='big_logo')),
                ('small_logo', models.ImageField(blank=True, null=True, upload_to='small_logo')),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_based_view', models.BooleanField(default=False)),
                ('process_based_view', models.BooleanField(default=False)),
                ('auto_assign_worker', models.BooleanField(default=False)),
                ('has_upload_limit', models.BooleanField(default=False)),
                ('upload_limit', models.IntegerField(default=100)),
                ('api_csv_separator', models.CharField(blank=True, max_length=5, null=True)),
                ('saml_sso_config', models.JSONField(blank=True, null=True)),
                ('show_sftp', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_url', models.URLField(blank=True, null=True)),
                ('page_classification_url', models.URLField(blank=True, null=True)),
                ('extra_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_types', to='master.extractionconfiguration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_page_labels', to='master.extractionconfiguration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_page_labels', to='master.mastertype')),
            ],
        ),
        migrations.CreateModel(
            name='MasterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('amount', 'Amount'), ('boolean', 'Boolean'), ('image', 'Image')], default='text', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ml_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('do_postprocessing', models.BooleanField(default=False)),
                ('is_multi_line', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('output_max_length', models.IntegerField(blank=True, null=True)),
                ('output_decimals_digit', models.IntegerField(blank=True, null=True)),
                ('output_date_formate', models.CharField(blank=True, max_length=10, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_fields', to='master.extractionconfiguration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
                ('page_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterpagelabel')),
            ],
        ),
        migrations.AddIndex(
            model_name='mastertype',
            index=models.Index(fields=['name'], name='mastertype_name_index'),
        ),
        migrations.AddIndex(
            model_name='mastertype',
            index=models.Index(fields=['code'], name='mastertype_code_index'),
        ),
        migrations.AddIndex(
            model_name='mastertype',
            index=models.Index(fields=['tag_name'], name='mastertype_tag_name_index'),
        ),
        migrations.AddIndex(
            model_name='mastertype',
            index=models.Index(fields=['is_active'], name='mastertype_is_active_index'),
        ),
        migrations.AddIndex(
            model_name='masterpagelabel',
            index=models.Index(fields=['configuration'], name='master_mast_configu_f80614_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpagelabel',
            index=models.Index(fields=['code'], name='master_mast_code_a7e989_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpagelabel',
            index=models.Index(fields=['tag_name'], name='master_mast_tag_nam_022f74_idx'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='masterfield',
            order_with_respect_to='configuration',
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['configuration'], name='master_mast_configu_6e26b3_idx'),
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['page_label'], name='master_mast_page_la_c7d583_idx'),
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['name'], name='master_mast_name_b0e515_idx'),
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['code'], name='master_mast_code_ccbbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['tag_name'], name='master_mast_tag_nam_1f9449_idx'),
        ),
        migrations.AddIndex(
            model_name='masterfield',
            index=models.Index(fields=['is_active'], name='master_mast_is_acti_83a895_idx'),
        ),
    ]
