# Generated by Django 4.1.9 on 2023-11-22 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0002_alter_masterpagelabel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfiguration',
            name='max_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='masterfield',
            name='do_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='masterpagelabel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.mastertype'),
        ),
        migrations.CreateModel(
            name='SetFieldScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('expected_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='DigitalMasterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('amount', 'Amount'), ('boolean', 'Boolean'), ('image', 'Image')], default='text', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ml_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('do_postprocessing', models.BooleanField(default=False)),
                ('is_multi_line', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('header', models.CharField(max_length=100)),
                ('output_max_length', models.IntegerField(blank=True, null=True)),
                ('output_decimals_digit', models.IntegerField(blank=True, null=True)),
                ('output_date_formate', models.CharField(blank=True, max_length=10, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_master_fields', to='master.extractionconfiguration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'configuration',
            },
        ),
        migrations.AddIndex(
            model_name='digitalmasterfield',
            index=models.Index(fields=['configuration'], name='master_digi_configu_757611_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalmasterfield',
            index=models.Index(fields=['name'], name='master_digi_name_ffd521_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalmasterfield',
            index=models.Index(fields=['code'], name='master_digi_code_e07e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalmasterfield',
            index=models.Index(fields=['tag_name'], name='master_digi_tag_nam_077699_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalmasterfield',
            index=models.Index(fields=['is_active'], name='master_digi_is_acti_dede74_idx'),
        ),
    ]
