# Generated by Django 4.1.9 on 2023-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_accountconfiguration_max_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmasterfield',
            name='field_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setfieldscore',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setfieldscore',
            name='weightage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
