# Generated by Django 4.1.9 on 2023-12-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_delete_setfieldscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmasterfield',
            name='output_date_formate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='digitalmasterfield',
            name='output_decimals_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalmasterfield',
            name='output_max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
