# Generated by Django 4.1.9 on 2023-12-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_accountconfiguration_salt_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfiguration',
            name='salt_value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='secret_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
