# Generated by Django 4.1.9 on 2024-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_accountconfiguration_salt_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmasterfield',
            name='allow_weightage',
            field=models.BooleanField(default=False),
        ),
    ]
