# Generated by Django 4.1.9 on 2023-10-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('user_agent_info', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_object', models.CharField(blank=True, max_length=100, null=True)),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('login_IP', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('exec_time', models.FloatField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
