# Generated by Django 4.1.9 on 2023-10-29 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claim_application', '0002_documentprocessreferenceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(choices=[('APPLICATION_DOCUMENT_SUBMITTED', 'Application Document Submitted'), ('EXTRACTION_START', 'Extraction Start'), ('EXTRACTION_COMPLETE', 'Extraction Complete'), ('EXTRACTION_ERROR', 'Extraction Error'), ('APPLICATION_DOCUMENT_PROCESSED', 'Application Document Processed'), ('APPLICATION_DOCUMENT_INVALID', 'Application Document Invalid'), ('APPLICATION_DOCUMENT_ERROR', 'Application Document Error')], default='APPLICATION_DOCUMENT_SUBMITTED', max_length=50)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], default='INFO', max_length=10)),
                ('notify', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('application_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='claim_application.applicationdocument')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
