# Generated by Django 4.1.9 on 2023-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0003_applicationdocumentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='digital_json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Digital Json'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
