# Generated by Django 4.1.9 on 2023-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0004_applicationdocument_digital_json_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='extracted_summary_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Extracted Summary PDF'),
        ),
        migrations.AddField(
            model_name='singledocument',
            name='type',
            field=models.CharField(choices=[('RAW', 'RAW'), ('PROCESSED', 'PROCESSED'), ('CONSOLIDATED', 'CONSOLIDATED')], default='RAW', max_length=20),
        ),
    ]
