# Generated by Django 4.1.9 on 2023-11-22 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_accountconfiguration_max_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claim_application', '0005_applicationdocument_extracted_summary_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('Holder', 'holder'), ('Nominee', 'nominee')], default='Holder', max_length=10)),
                ('customer_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('validation_name', models.CharField(max_length=50)),
                ('configuration_for', models.CharField(choices=[('document', 'Document')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='processed_digital_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='score_json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Score Json'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_front',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ValidationRuleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('validation_code', models.CharField(max_length=6)),
                ('validation_action', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('off', 'Off')], max_length=50)),
                ('validation_description', models.CharField(blank=True, max_length=256, null=True)),
                ('validation_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rule_engine', to='claim_application.validationconfiguration')),
            ],
            options={
                'unique_together': {('validation_configuration', 'validation_code')},
            },
        ),
        migrations.CreateModel(
            name='TemporaryValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimant_temp_validations', to='claim_application.claimant')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_temp_validations', to='master.masterfield')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_temp_validations', to='claim_application.page')),
                ('page_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagefield_temp_validations', to='claim_application.pagefield')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_validation_rule', to='claim_application.validationruleengine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('master_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterfield')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_scores', to='claim_application.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimantFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('value_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_amount', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_extracted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimant_fields', to='claim_application.claimant')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('digital_master_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.digitalmasterfield')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='claimant',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim_application.applicationdocument'),
        ),
        migrations.AddField(
            model_name='claimant',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimant_pages', to='claim_application.claimant'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['claimant'], name='claim_appli_claiman_ff1091_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['digital_master_field'], name='claim_appli_digital_fcde21_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['text'], name='claim_appli_text_965599_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['value_text'], name='claim_appli_value_t_262d70_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['value_date'], name='claim_appli_value_d_d5295f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['value_amount'], name='claim_appli_value_a_25805a_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['value_boolean'], name='claim_appli_value_b_7c931e_idx'),
        ),
        migrations.AddIndex(
            model_name='claimantfields',
            index=models.Index(fields=['is_active'], name='claim_appli_is_acti_b1010f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimant',
            index=models.Index(fields=['document'], name='claim_appli_documen_ceeb88_idx'),
        ),
        migrations.AddIndex(
            model_name='claimant',
            index=models.Index(fields=['is_active'], name='claim_appli_is_acti_32c8ff_idx'),
        ),
    ]
