# Generated by Django 4.1.9 on 2023-11-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0006_claimant_validationconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='field_type_matching',
            field=models.JSONField(blank=True, null=True, verbose_name='Score Json'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='name_to_original',
            field=models.JSONField(blank=True, null=True, verbose_name='Score Json'),
        ),
        migrations.AddField(
            model_name='pagefield',
            name='original_page_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='num_pages',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
