# Generated by Django 4.1.9 on 2023-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0007_applicationdocument_field_type_matching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='field_type_matching',
            field=models.JSONField(blank=True, null=True, verbose_name='Field Type Matching'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='name_to_original',
            field=models.JSONField(blank=True, null=True, verbose_name='Name to Original'),
        ),
    ]
