# Generated by Django 4.1.9 on 2023-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0008_alter_applicationdocument_field_type_matching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='ref_json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Reference Json'),
        ),
    ]
