# Generated by Django 4.1.9 on 2024-01-11 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claim_application', '0011_magiclinkhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRefName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Exported File')),
                ('csv_seperator', models.CharField(default=',', max_length=1)),
                ('status', models.CharField(choices=[('queued', 'In Queue'), ('processing', 'Processing'), ('completed', 'Success'), ('error', 'Error')], default='queued', max_length=50)),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'Csv')], default='excel', max_length=5)),
                ('output_type', models.CharField(choices=[('document', 'Document'), ('digital_json', 'Digital Json')], default='document', max_length=20)),
                ('extra_params', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', related_query_name='%(app_label)s_%(class)ss_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', related_query_name='%(app_label)s_%(class)ss_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['start_date'], name='claim_appli_start_d_7cb66c_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['end_date'], name='claim_appli_end_dat_017d95_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['status'], name='claim_appli_status_36c8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['start_date', 'end_date'], name='claim_appli_start_d_830661_idx'),
        ),
    ]
