# Generated by Django 4.1.9 on 2024-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_application', '0012_exportrefname_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='date_of_intimation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='proposal_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
